#!/usr/bin/env python
import sys
from pyromanager import ui

if __name__ == '__main__':
    try:
        __cli__ = ui.Cli()
        sys.exit( __cli__.main() )
    except KeyboardInterrupt:
        print "Interrupted. Exiting gracefully."
